#ifndef __APP_MAIN_H__
#define __APP_MAIN_H__


typedef enum{
    APP_NOT_INIT,
    APP_INIT_DONE,
    APP_RUNNING,
    APP_INTERRUPTED,
}app_status_t;


typedef enum overall_state{
    OVERALL_STATE_POWER_ON,
    OVERALL_STATE_NETWORK_CONFIGURING,
    OVERALL_STATE_CONNECTING_WIFI,
    OVERALL_STATE_RENEWAL_OVERDUE,
    OVERALL_STATE_ACTIVATION,
    OVERALL_STATE_OTA_UPGRADING,
    OVERALL_STATE_NETWORK_INTERRUPTED,
    OVERALL_STATE_REGISTERING,
    OVERALL_STATE_IDLE,
    OVERALL_STATE_DIALOG_INITIATING,
    OVERALL_STATE_DIALOG_SPEAKING,
    OVERALL_STATE_DIALOG_LISTENING,
}overall_state_t;
app_status_t get_network_status();

overall_state_t get_overall_state();

#endif