#ifndef _APP_MSG_H_
#define _APP_MSG_H_

#include "app_core.h"
#include "os/os_api.h"

#define MSG_FROM_APP  (Q_MSG + 1)

typedef enum {
    APP_MODE_IDLE,
    APP_MODE_NET,
    APP_MODE_BT,
    APP_MODE_LOCAL,
    APP_MODE_LINEIN,
    APP_MODE_PC,
    APP_MODE_FM,
    APP_MODE_RECORDER,
    APP_MODE_SINK,
    APP_MODE_UPDATE,
    APP_MODE_POWERON,
    APP_MODE_RTC,
    APP_MODE_SPDIF,
    APP_MODE_SYSTEM,
    APP_MODE_REC,
    APP_MODE_PHOTO,
    APP_MODE_DEC,
    APP_MODE_MAX,
} app_mode_t;

struct app_event_handler {
    int event;
    int from;
    int (*handler)(void *event);
};


#define REGISTER_APP_EVENT_HANDLER(event_handler) \
    static const struct app_event_handler event_handler SEC_USED(.app_event_handler)

extern const struct app_event_handler app_event_handler_begin[];
extern const struct app_event_handler app_event_handler_end[];

#define for_each_app_event_handler(p) \
    for (p = app_event_handler_begin; p < app_event_handler_end; p++)


enum {
    APP_MSG_NULL = 0,

    APP_MSG_SUSPEND,
    APP_MSG_RESUME,
    APP_MSG_STOP,


    APP_MSG_SYSTEM_BOTTOM,
    APP_MSG_SYSTEM_SD_CARD_FORMAT,
    APP_MSG_SYSTEM_SET_CONFIG,
    APP_MSG_SYSTEM_TOP,

    APP_MSG_REC_BOTTOM,
    APP_MSG_REC_STATE,
    APP_MSG_REC_PHOTO,
    APP_MSG_REC_MODE,
    APP_MSG_REC_MUTE,
    APP_MSG_REC_MAIN,
    APP_MSG_REC_SET_CONFIG,
    APP_MSG_REC_CHANGE_STATUS,
    APP_MSG_REC_PARKING_STATUS,
    APP_MSG_REC_GET_REMAIN_TIME,
    APP_MSG_REC_CONTROL,
    APP_MSG_REC_LOCK_FILE,
    APP_MSG_REC_SWITCH_WIN,
    APP_MSG_REC_TOP,

    APP_MSG_PHOTO_BOTTOM,
    APP_MSG_PHOTO_SWITCH,
    APP_MSG_PHOTO_DELAY,
    APP_MSG_PHOTO_TAKE_MAIN,
    APP_MSG_PHOTO_TAKE_CONTROL,
    APP_MSG_PHOTO_TAKE_SET_CONFIG,
    APP_MSG_PHOTO_TAKE_GET_CONFIG,
    APP_MSG_PHOTO_TAKE_SWITCH_WIN,
    APP_MSG_PHOTO_TOP,

    APP_MSG_DEC_BOTTOM,
    APP_MSG_DEC_PAUSE,
    APP_MSG_DEC_FR,
    APP_MSG_DEC_FF,
    APP_MSG_DEC_FILE,
    APP_MSG_DEC_SCAN_DOWN,
    APP_MSG_DEC_SCAN_UP,
    APP_MSG_DEC_MAIN,
    APP_MSG_DEC_CHANGE_STATUS,
    APP_MSG_DEC_SET_CONFIG,
    APP_MSG_DEC_OPEN_FILE,
    APP_MSG_DEC_PREV_NEXT_CONTROL,
    APP_MSG_DEC_CONTROL,
    APP_MSG_DEC_GET_FRAME,
    APP_MSG_DEC_SET_AUDIO_VOLUME,
    APP_MSG_DEC_SET_PLAY_SPEED,
    APP_MSG_DEC_CUR_PAGE,
    APP_MSG_DEC_TOP,

    APP_MSG_LOCAL_MUSIC_BOTTOM,
    APP_MSG_LOCAL_MUSIC_PP,
    APP_MSG_LOCAL_MUSIC_PLAY,
    APP_MSG_LOCAL_MUSIC_PAUSE,
    APP_MSG_LOCAL_MUSIC_PREV,
    APP_MSG_LOCAL_MUSIC_NEXT,
    APP_MSG_LOCAL_MUSIC_CHANGE_DEV,
    APP_MSG_LOCAL_MUSIC_AUTO_NEXT_DEV,
    APP_MSG_LOCAL_MUSIC_PLAY_NEXT_FOLDER,
    APP_MSG_LOCAL_MUSIC_PLAY_PREV_FOLDER,
    APP_MSG_LOCAL_MUSIC_PLAY_FIRST,
    APP_MSG_LOCAL_MUSIC_PLAY_REC_FOLDER_SWITCH,		//播放录音文件
    APP_MSG_LOCAL_MUSIC_DELETE_CUR_FILE,				//删除当前文件
    APP_MSG_LOCAL_MUSIC_MOUNT_PLAY_START,
    APP_MSG_LOCAL_MUSIC_PLAY_START,
    APP_MSG_LOCAL_MUSIC_PLAY_START_BY_SCLUST,
    APP_MSG_LOCAL_MUSIC_PLAY_START_BY_DEV,
    APP_MSG_LOCAL_MUSIC_FR,
    APP_MSG_LOCAL_MUSIC_FF,
    APP_MSG_LOCAL_MUSIC_DEC_ERR,
    APP_MSG_LOCAL_MUSIC_PLAYER_END,
    APP_MSG_LOCAL_MUSIC_CHANGE_REPEAT,
    APP_MSG_LOCAL_MUSIC_SPEED_UP,
    APP_MSG_LOCAL_MUSIC_SPEED_DOWN,
    APP_MSG_LOCAL_MUSIC_PITCH_UP,
    APP_MSG_LOCAL_MUSIC_PITCH_DOWN,
    APP_MSG_LOCAL_MUSIC_PLAYER_AB_REPEAT_SWITCH,
    APP_MSG_LOCAL_MUSIC_PLAY_BY_NUM,
    APP_MSG_LOCAL_MUSIC_PLAY_START_AT_DEST_TIME,
    APP_MSG_LOCAL_MUSIC_FILE_NUM_CHANGED,
    APP_MSG_LOCAL_MUSIC_REPEAT_MODE_CHANGED,
    APP_MSG_LOCAL_MUSIC_PLAY_STATUS,
    APP_MSG_LOCAL_MUSIC_TOP,

    APP_MSG_NET_MUSIC_BOTTOM,
    APP_MSG_NET_MUSIC_PP,
    APP_MSG_NET_MUSIC_PLAY,
    APP_MSG_NET_MUSIC_PAUSE,
    APP_MSG_NET_MUSIC_PREV,
    APP_MSG_NET_MUSIC_NEXT,
    APP_MSG_NET_MUSIC_PLAY_START,
    APP_MSG_NET_MUSIC_PLAY_STOP,
    APP_MSG_NET_MUSIC_PLAY_END,
    APP_MSG_NET_MUSIC_FR,
    APP_MSG_NET_MUSIC_FF,
    APP_MSG_NET_MUSIC_DEC_ERR,
    APP_MSG_NET_MUSIC_VOL_SET,
    APP_MSG_NET_MUSIC_VOL_CHANGED,
    APP_MSG_NET_MUSIC_SPEED_UP,
    APP_MSG_NET_MUSIC_SPEED_DOWN,
    APP_MSG_NET_MUSIC_PITCH_UP,
    APP_MSG_NET_MUSIC_PITCH_DOWN,
    APP_MSG_NET_MUSIC_PLAYER_AB_REPEAT_SWITCH,
    APP_MSG_NET_MUSIC_PLAY_START_AT_DEST_TIME,
    APP_MSG_NET_MUSIC_PLAY_STATUS,
    APP_MSG_NET_MUSIC_TOP,

    APP_MSG_LINEIN_MUSIC_BOTTOM,
    APP_MSG_LINEIN_MUSIC_PP,
    APP_MSG_LINEIN_MUSIC_PLAY,
    APP_MSG_LINEIN_MUSIC_PAUSE,
    APP_MSG_LINEIN_MUSIC_PITCH_UP,
    APP_MSG_LINEIN_MUSIC_PITCH_DOWN,
    APP_MSG_LINEIN_MUSIC_TOP,

    APP_MSG_PC_MUSIC_BOTTOM,
    APP_MSG_PC_MUSIC_PP,
    APP_MSG_PC_MUSIC_MOUNT,
    APP_MSG_PC_MUSIC_PLAY,
    APP_MSG_PC_MUSIC_PAUSE,
    APP_MSG_PC_MUSIC_PREV,
    APP_MSG_PC_MUSIC_NEXT,
    APP_MSG_PC_MUSIC_VOL_UP,
    APP_MSG_PC_MUSIC_VOL_DOWN,
    APP_MSG_PC_MUSIC_CALL_HANGUP,
    APP_MSG_PC_MUSIC_PITCH_UP,
    APP_MSG_PC_MUSIC_PITCH_DOWN,
    APP_MSG_PC_MUSIC_TOP,

    APP_MSG_BT_BOTTOM,
    APP_MSG_BT_MUSIC_PP,
    APP_MSG_BT_MUSIC_PLAY,
    APP_MSG_BT_MUSIC_PAUSE,
    APP_MSG_BT_MUSIC_NEXT,
    APP_MSG_BT_MUSIC_PREV,
    APP_MSG_BT_MUSIC_PITCH_UP,
    APP_MSG_BT_MUSIC_PITCH_DOWN,
    APP_MSG_BT_DISCONNECT,
    APP_MSG_BT_OPEN_PAGE_SCAN,
    APP_MSG_BT_CLOSE_PAGE_SCAN,
    APP_MSG_BT_ENTER_SNIFF,
    APP_MSG_BT_EXIT_SNIFF,
    APP_MSG_BT_A2DP_START,
    APP_MSG_BT_A2DP_PLAY,
    APP_MSG_BT_A2DP_PAUSE,
    APP_MSG_BT_A2DP_STOP,
    APP_MSG_BT_SEND_A2DP_PLAY_CMD,
    APP_MSG_BT_A2DP_NO_ENERGY,
    APP_MSG_BT_PAGE_DEVICE,
    APP_MSG_BT_IN_PAIRING_MODE,
    APP_MSG_BT_CALL_ANSWER,
    APP_MSG_BT_CALL_HANGUP,
    APP_MSG_BT_CALL_LAST_NO,
    APP_MSG_BT_CALL_THREE_WAY_ANSWER1,
    APP_MSG_BT_CALL_THREE_WAY_ANSWER2,
    APP_MSG_BT_CALL_SWITCH,
    APP_MSG_BT_HID_CONTROL,
    APP_MSG_BT_OPEN_SIRI,
    APP_MSG_BT_VOL_UP,
    APP_MSG_BT_VOL_DOWN,
    APP_MSG_BT_VOL_SET,
    APP_MSG_BT_LOW_LANTECY,
    APP_MSG_BT_TOP,

    APP_MSG_TWS_BOTTOM,
    APP_MSG_TWS_PAIRED,
    APP_MSG_TWS_UNPAIRED,
    APP_MSG_TWS_PAIR_SUSS,
    APP_MSG_TWS_CONNECTED,
    APP_MSG_TWS_WAIT_PAIR,                      // 等待配对
    APP_MSG_TWS_START_PAIR,                     // 手动发起配对
    APP_MSG_TWS_START_CONN,                     // 开始回连TWS
    APP_MSG_TWS_REMOVE_PAIR,                    // 取消配对
    APP_MSG_TWS_START_REMOVE_PAIR,              // 如果没有配对则发起配对，如果配对了则取消配对
    APP_MSG_TWS_WAIT_CONN,                      // 等待TWS连接
    APP_MSG_TWS_START_PAIR_AND_CONN_PROCESS,    // 执行配对和连接的默认流程
    APP_MSG_TWS_POWERON_PAIR_TIMEOUT,           // TWS开机配对超时
    APP_MSG_TWS_POWERON_CONN_TIMEOUT,           // TWS开机回连超时
    APP_MSG_TWS_START_PAIR_TIMEOUT,
    APP_MSG_TWS_START_CONN_TIMEOUT,
    APP_MSG_TWS_SLAVE_REJECT_CONN,
    APP_MSG_TWS_TOP,

    APP_MSG_SINK_MUSIC_BOTTOM,
    APP_MSG_SINK_MUSIC_PP,
    APP_MSG_SINK_MUSIC_PLAY,
    APP_MSG_SINK_MUSIC_PAUSE,
    APP_MSG_SINK_MUSIC_PREV,
    APP_MSG_SINK_MUSIC_NEXT,
    APP_MSG_SINK_MUSIC_VOL_UP,
    APP_MSG_SINK_MUSIC_VOL_DOWN,
    APP_MSG_SINK_MUSIC_TOP,

    APP_MSG_RECORDER_BOTTOM,
    APP_MSG_RECORDER_PP,
    APP_MSG_RECORDER_TOP,

    APP_MSG_FM_INIT_OK,
    APP_MSG_FM_REFLASH,
    APP_MSG_FM_STATION,
    APP_MSG_FM_SCAN_ALL,
    APP_MSG_FM_SCAN_ALL_DOWN,
    APP_MSG_FM_SCAN_ALL_UP,
    APP_MSG_FM_SCAN_DOWN,
    APP_MSG_FM_SCAN_UP,
    APP_MSG_FM_PREV_STATION,
    APP_MSG_FM_NEXT_STATION,
    APP_MSG_FM_PREV_FREQ,
    APP_MSG_FM_NEXT_FREQ,

    APP_MSG_MAX_VOL,
    APP_MSG_MIN_VOL,
    APP_MSG_SYS_MUTE,

    APP_MSG_GOTO_MODE,
    APP_MSG_GOTO_NEXT_MODE,
    APP_MSG_ENTER_MODE,
    APP_MSG_EXIT_MODE,

    APP_MSG_POWER_ON,
    APP_MSG_POWER_OFF,

    APP_MSG_ENC_START,
    APP_MSG_REVERB_OPNE,
    APP_MSG_MIC_VOL_UP,
    APP_MSG_MIC_VOL_DOWN,
    APP_MSG_MIC_BASS_UP,
    APP_MSG_MIC_BASS_DOWN,
    APP_MSG_MIC_TREBLE_UP,
    APP_MSG_MIC_TREBLE_DOWN,

    APP_MSG_CHANGE_MODE,
    APP_MSG_SWITCH_SOUND_EFFECT,
    APP_MSG_MIC_EFFECT_ON_OFF,
    APP_MSG_SWITCH_MIC_EFFECT,
    APP_MSG_VOCAL_REMOVE,

    APP_MSG_LINEIN_PLAY_STATUS,
    APP_MSG_INPUT_FILE_NUM,
    APP_MSG_RTC_SET,
    APP_MSG_RTC_UP,
    APP_MSG_RTC_DOWN,
    APP_MSG_RTC_SW,
    APP_MSG_RTC_SW_POS,
    APP_MSG_EQ_CHANGED,
    APP_MSG_MUTE_CHANGED,
};

int app_send_message(int msg, int argc, ...);

void app_send_message_from(int from, int argc, int *msg);

void ai_app_local_event_notify(u8 status);

bool current_app_in_mode(app_mode_t mode);

app_mode_t get_current_app_mode(void);

void app_mode_change(app_mode_t mode);

void app_mode_change_replace(app_mode_t mode);

void app_mode_change_next(void);

void app_mode_go_back(void);

#endif

